"""
Django settings for ascourier project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'qvyc)v2xpqz8)1=dkf2i)if*q7ad53gxswafwm+n7k(5_*9zvl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*',]


# Application definition

INSTALLED_APPS = [
    'adminlte3_theme',
    'adminlte3',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles', 
    'bootstrap4',
    'social_django',
    'core.apps.CoreConfig',
    'channels'
    
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.ProfileMiddlware',
]

ROOT_URLCONF = 'ascourier.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'ascourier.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

LOGIN_URL = '/sign-in/'
LOGIN_REDIRECT_URL = '/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

AUTHENTICATION_BACKENDS = (
    'social_core.backends.facebook.FacebookOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

SOCIAL_AUTH_FACEBOOK_KEY = "864173640944489"
SOCIAL_AUTH_FACEBOOK_SECRET = "69f000909238d229bd54a9d3ff8af4cb"
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
    'fields': 'id, name, email'
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'raselahmed4star@gmail.com'
EMAIL_HOST_PASSWORD = '09638231930'
DEFAULT_FROM_EMAIL = 'As Courier <no-reply@ascourier.localhost>'

FIREBASE_ADMIN_CREDENTIAL = os.path.join(BASE_DIR, "ascourier-81b1f-firebase-adminsdk-oahbt-25fc59c054.json")

STRIPE_API_PUBLIC_KEY = "pk_test_51IOP4ZHKS9pvoGJ9ed4eg49v4CleQPOlE5oOX6fYXvcL14hz4taSI24SIfsSNoqDSUGWbckFmh7n2KOMA7JnRvUf009aV9JA3c"
STRIPE_API_SECRET_KEY = "sk_test_51IOP4ZHKS9pvoGJ96R9TALAYJ8ynm60DZlqGkoQK44oLql05F4Yd2zzFXksuSWN2Km1IbpmSFBAbi0cPTWXNKJy900mDmSBuXq"
GOOGLE_MAP_API_KEY = "AIzaSyBRwPydLkK60QdolCVOY6D90RPDhz5FTx4"
# GOOGLE_MAP_API_KEY = "AIzaSyAGAW1PiDBoJSRcaY2F6vgG2npoFMBk20Q"


PAYPAL_MODE = "sandbox"
PAYPAL_CLIENT_ID = "AWa2x5aDpSLGggSHAVvOSa50TEn57uPkgmqzqfpEMsBOBRAjsAGxc6qG962mRtLoS1-2SW2LsLF1l0lb"
PAYPAL_CLIENT_SECRET = "EEQ1zXsbTRHiyiVpYwcVFrDKT3Go-aozZTFgsIXXCnKdlqfMKPqiCY9YXpLf27ob6A7qVAGH3r26_-2h"

NOTIFICATION_URL = "https://desolate-stream-18620.herokuapp.com/"

ASGI_APPLICATION = "ascourier.asgi.application"
#  Channels
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": ['YOUR_HEROKU_REDIS_URL'],
        },
    },
}

# Activate Django Heroku
import django_on_heroku
django_on_heroku.settings(locals())